server:
  port: 8222

#spring:
#  profiles: default
#  rabbitmq:
#    host: localhost
#    port: 15672
#    password: guest
#    username: guest
#    virtual-host: /
#  jpa:
#    hibernate:
#      ddl-auto: create
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#  datasource:
#    url: "jdbc:postgresql://localhost:5432/postgres?currentSchema=sampleschema"
#    username: postgres
#    password: postgres123
#    driver-class-name: org.postgresql.Driver
